version: '2'
services:
  db:
    image: mysql
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
     - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: gaoy
      MYSQL_PASSWORD: gaoy1234

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:53306
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_USER: gaoy          
      WORDPRESS_DB_PASSWORD: gaoy1234

  nginx:
    depends_on:
      - wordpress 
    image: nginx 
    volumes:
      - "./data/log:/var/log/nginx"
      - "./data/cnf/conf.d/:/etc/nginx/conf.d/"
      - "./data/htdocs:/usr/share/nginx/html"
    restart: always
    ports:
     - "80:80"
