version: '2'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - "./data/htdocs:/var/www/html"
    ports:
      - "10.116.207.174:8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 10.116.207.174:53306
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_USER: gaoy
      WORDPRESS_DB_PASSWORD: gaoy1234
